
*** 81 configurations x 1.0 iterations each

1 | Fri Oct 29 19:48:53 2021 | lowest loss so far: inf (run -1)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
137/137 [==============================] - ETA: 0s - loss: 0.5406 - accuracy: 0.7995WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
137/137 [==============================] - 17s 108ms/step - loss: 0.5406 - accuracy: 0.7995 - val_loss: 0.4038 - val_accuracy: 0.8461
Epoch 2/10
137/137 [==============================] - 15s 106ms/step - loss: 0.3273 - accuracy: 0.8843 - val_loss: 0.3485 - val_accuracy: 0.8637
Epoch 3/10
137/137 [==============================] - 15s 113ms/step - loss: 0.2686 - accuracy: 0.9052 - val_loss: 0.3341 - val_accuracy: 0.8619
Epoch 4/10
137/137 [==============================] - 16s 113ms/step - loss: 0.2398 - accuracy: 0.9155 - val_loss: 0.3449 - val_accuracy: 0.8628
Epoch 5/10
137/137 [==============================] - 16s 115ms/step - loss: 0.2176 - accuracy: 0.9246 - val_loss: 0.3456 - val_accuracy: 0.8637
Epoch 6/10
137/137 [==============================] - 16s 113ms/step - loss: 0.2084 - accuracy: 0.9256 - val_loss: 0.3573 - val_accuracy: 0.8619
Epoch 7/10
137/137 [==============================] - 16s 115ms/step - loss: 0.1922 - accuracy: 0.9330 - val_loss: 0.3598 - val_accuracy: 0.8672
Epoch 8/10
137/137 [==============================] - 15s 107ms/step - loss: 0.1805 - accuracy: 0.9375 - val_loss: 0.3755 - val_accuracy: 0.8584
Epoch 9/10
137/137 [==============================] - 15s 111ms/step - loss: 0.1726 - accuracy: 0.9412 - val_loss: 0.3898 - val_accuracy: 0.8584
Epoch 10/10
137/137 [==============================] - 15s 107ms/step - loss: 0.1657 - accuracy: 0.9434 - val_loss: 0.4033 - val_accuracy: 0.8628
36/36 [==============================] - 0s 12ms/step - loss: 0.1473 - accuracy: 0.9533

155 seconds.

2 | Fri Oct 29 19:51:28 2021 | lowest loss so far: 0.1473 (run 1)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
2046/2046 [==============================] - ETA: 0s - loss: 0.3536 - accuracy: 0.8550WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
2046/2046 [==============================] - 183s 89ms/step - loss: 0.3536 - accuracy: 0.8550 - val_loss: 0.3345 - val_accuracy: 0.8566
Epoch 2/10
2046/2046 [==============================] - 179s 88ms/step - loss: 0.2485 - accuracy: 0.9033 - val_loss: 0.3138 - val_accuracy: 0.8690
Epoch 3/10
2046/2046 [==============================] - 179s 87ms/step - loss: 0.2028 - accuracy: 0.9264 - val_loss: 0.3310 - val_accuracy: 0.8707
Epoch 4/10
2046/2046 [==============================] - 178s 87ms/step - loss: 0.1740 - accuracy: 0.9366 - val_loss: 0.3462 - val_accuracy: 0.8769
Epoch 5/10
2046/2046 [==============================] - 177s 87ms/step - loss: 0.1487 - accuracy: 0.9465 - val_loss: 0.3625 - val_accuracy: 0.8777
Epoch 6/10
2046/2046 [==============================] - 178s 87ms/step - loss: 0.1285 - accuracy: 0.9540 - val_loss: 0.3885 - val_accuracy: 0.8698
Epoch 7/10
2046/2046 [==============================] - 178s 87ms/step - loss: 0.1129 - accuracy: 0.9612 - val_loss: 0.4322 - val_accuracy: 0.8698
Epoch 8/10
2046/2046 [==============================] - 178s 87ms/step - loss: 0.1042 - accuracy: 0.9655 - val_loss: 0.4671 - val_accuracy: 0.8654
Epoch 9/10
2046/2046 [==============================] - 178s 87ms/step - loss: 0.0922 - accuracy: 0.9700 - val_loss: 0.4986 - val_accuracy: 0.8514
Epoch 10/10
2046/2046 [==============================] - 178s 87ms/step - loss: 0.0834 - accuracy: 0.9735 - val_loss: 0.4899 - val_accuracy: 0.8637
36/36 [==============================] - 0s 12ms/step - loss: 0.1067 - accuracy: 0.9701

1787 seconds.

3 | Fri Oct 29 20:21:15 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 50).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 50).
137/137 [==============================] - ETA: 0s - loss: 0.4957 - accuracy: 0.7936WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 50).
137/137 [==============================] - 7s 36ms/step - loss: 0.4957 - accuracy: 0.7936 - val_loss: 0.3678 - val_accuracy: 0.8514
Epoch 2/10
137/137 [==============================] - 4s 29ms/step - loss: 0.3025 - accuracy: 0.8840 - val_loss: 0.3526 - val_accuracy: 0.8531
Epoch 3/10
137/137 [==============================] - 4s 30ms/step - loss: 0.2652 - accuracy: 0.9014 - val_loss: 0.3350 - val_accuracy: 0.8672
Epoch 4/10
137/137 [==============================] - 4s 29ms/step - loss: 0.2429 - accuracy: 0.9118 - val_loss: 0.3368 - val_accuracy: 0.8628
Epoch 5/10
137/137 [==============================] - 4s 30ms/step - loss: 0.2266 - accuracy: 0.9186 - val_loss: 0.3441 - val_accuracy: 0.8619
Epoch 6/10
137/137 [==============================] - 4s 30ms/step - loss: 0.2121 - accuracy: 0.9268 - val_loss: 0.3553 - val_accuracy: 0.8637
Epoch 7/10
137/137 [==============================] - 4s 29ms/step - loss: 0.2007 - accuracy: 0.9303 - val_loss: 0.3548 - val_accuracy: 0.8698
Epoch 8/10
137/137 [==============================] - 4s 28ms/step - loss: 0.1873 - accuracy: 0.9335 - val_loss: 0.3538 - val_accuracy: 0.8619
Epoch 9/10
137/137 [==============================] - 4s 29ms/step - loss: 0.1809 - accuracy: 0.9384 - val_loss: 0.3880 - val_accuracy: 0.8558
Epoch 10/10
137/137 [==============================] - 4s 29ms/step - loss: 0.1725 - accuracy: 0.9407 - val_loss: 0.3942 - val_accuracy: 0.8566
36/36 [==============================] - 0s 4ms/step - loss: 0.1919 - accuracy: 0.9349

43 seconds.

4 | Fri Oct 29 20:21:58 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
108/108 [==============================] - ETA: 0s - loss: 0.4966 - accuracy: 0.8038WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
108/108 [==============================] - 13s 105ms/step - loss: 0.4966 - accuracy: 0.8038 - val_loss: 0.3646 - val_accuracy: 0.8522
Epoch 2/10
108/108 [==============================] - 10s 96ms/step - loss: 0.3014 - accuracy: 0.8878 - val_loss: 0.3386 - val_accuracy: 0.8637
Epoch 3/10
108/108 [==============================] - 10s 96ms/step - loss: 0.2562 - accuracy: 0.9053 - val_loss: 0.3253 - val_accuracy: 0.8716
Epoch 4/10
108/108 [==============================] - 10s 96ms/step - loss: 0.2333 - accuracy: 0.9160 - val_loss: 0.3370 - val_accuracy: 0.8610
Epoch 5/10
108/108 [==============================] - 10s 95ms/step - loss: 0.2142 - accuracy: 0.9231 - val_loss: 0.3426 - val_accuracy: 0.8698
Epoch 6/10
108/108 [==============================] - 10s 95ms/step - loss: 0.2005 - accuracy: 0.9286 - val_loss: 0.3580 - val_accuracy: 0.8672
Epoch 7/10
108/108 [==============================] - 10s 96ms/step - loss: 0.1881 - accuracy: 0.9343 - val_loss: 0.3771 - val_accuracy: 0.8566
Epoch 8/10
108/108 [==============================] - 10s 96ms/step - loss: 0.1750 - accuracy: 0.9385 - val_loss: 0.3891 - val_accuracy: 0.8619
Epoch 9/10
108/108 [==============================] - 10s 96ms/step - loss: 0.1658 - accuracy: 0.9433 - val_loss: 0.4074 - val_accuracy: 0.8549
Epoch 10/10
108/108 [==============================] - 10s 97ms/step - loss: 0.1601 - accuracy: 0.9438 - val_loss: 0.4087 - val_accuracy: 0.8566
36/36 [==============================] - 0s 11ms/step - loss: 0.1795 - accuracy: 0.9366

107 seconds.

5 | Fri Oct 29 20:23:45 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 190).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 190).
108/108 [==============================] - ETA: 0s - loss: 0.4695 - accuracy: 0.7913WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 190).
108/108 [==============================] - 18s 150ms/step - loss: 0.4695 - accuracy: 0.7913 - val_loss: 0.3490 - val_accuracy: 0.8610
Epoch 2/10
108/108 [==============================] - 15s 140ms/step - loss: 0.2903 - accuracy: 0.8904 - val_loss: 0.3296 - val_accuracy: 0.8646
Epoch 3/10
108/108 [==============================] - 15s 140ms/step - loss: 0.2551 - accuracy: 0.9053 - val_loss: 0.3216 - val_accuracy: 0.8716
Epoch 4/10
108/108 [==============================] - 15s 139ms/step - loss: 0.2295 - accuracy: 0.9144 - val_loss: 0.3390 - val_accuracy: 0.8637
Epoch 5/10
108/108 [==============================] - 15s 140ms/step - loss: 0.2114 - accuracy: 0.9231 - val_loss: 0.3446 - val_accuracy: 0.8698
Epoch 6/10
108/108 [==============================] - 15s 140ms/step - loss: 0.1962 - accuracy: 0.9281 - val_loss: 0.3422 - val_accuracy: 0.8690
Epoch 7/10
108/108 [==============================] - 15s 140ms/step - loss: 0.1818 - accuracy: 0.9352 - val_loss: 0.3675 - val_accuracy: 0.8646
Epoch 8/10
108/108 [==============================] - 15s 139ms/step - loss: 0.1731 - accuracy: 0.9371 - val_loss: 0.3891 - val_accuracy: 0.8531
Epoch 9/10
108/108 [==============================] - 15s 140ms/step - loss: 0.1633 - accuracy: 0.9422 - val_loss: 0.3995 - val_accuracy: 0.8575
Epoch 10/10
108/108 [==============================] - 15s 139ms/step - loss: 0.1548 - accuracy: 0.9448 - val_loss: 0.3982 - val_accuracy: 0.8584
36/36 [==============================] - 1s 14ms/step - loss: 0.1393 - accuracy: 0.9577

155 seconds.

6 | Fri Oct 29 20:26:20 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
410/410 [==============================] - ETA: 0s - loss: 0.3913 - accuracy: 0.8307WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
410/410 [==============================] - 33s 78ms/step - loss: 0.3913 - accuracy: 0.8307 - val_loss: 0.3310 - val_accuracy: 0.8681
Epoch 2/10
410/410 [==============================] - 31s 75ms/step - loss: 0.2629 - accuracy: 0.9013 - val_loss: 0.3148 - val_accuracy: 0.8672
Epoch 3/10
410/410 [==============================] - 31s 76ms/step - loss: 0.2217 - accuracy: 0.9158 - val_loss: 0.3264 - val_accuracy: 0.8742
Epoch 4/10
410/410 [==============================] - 31s 76ms/step - loss: 0.1940 - accuracy: 0.9266 - val_loss: 0.3266 - val_accuracy: 0.8707
Epoch 5/10
410/410 [==============================] - 31s 76ms/step - loss: 0.1724 - accuracy: 0.9362 - val_loss: 0.3430 - val_accuracy: 0.8734
Epoch 6/10
410/410 [==============================] - 31s 75ms/step - loss: 0.1536 - accuracy: 0.9435 - val_loss: 0.3740 - val_accuracy: 0.8654
Epoch 7/10
410/410 [==============================] - 31s 76ms/step - loss: 0.1410 - accuracy: 0.9500 - val_loss: 0.3980 - val_accuracy: 0.8558
Epoch 8/10
410/410 [==============================] - 31s 75ms/step - loss: 0.1266 - accuracy: 0.9538 - val_loss: 0.4528 - val_accuracy: 0.8593
Epoch 9/10
410/410 [==============================] - 31s 76ms/step - loss: 0.1186 - accuracy: 0.9592 - val_loss: 0.4481 - val_accuracy: 0.8566
Epoch 10/10
410/410 [==============================] - 31s 75ms/step - loss: 0.1096 - accuracy: 0.9618 - val_loss: 0.4887 - val_accuracy: 0.8619
36/36 [==============================] - 0s 9ms/step - loss: 0.1126 - accuracy: 0.9630

314 seconds.

7 | Fri Oct 29 20:31:34 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 80).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 80).
227/228 [============================>.] - ETA: 0s - loss: 0.4634 - accuracy: 0.8063WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 80).
228/228 [==============================] - 12s 48ms/step - loss: 0.4630 - accuracy: 0.8065 - val_loss: 0.3638 - val_accuracy: 0.8408
Epoch 2/10
228/228 [==============================] - 10s 44ms/step - loss: 0.3029 - accuracy: 0.8833 - val_loss: 0.3427 - val_accuracy: 0.8619
Epoch 3/10
228/228 [==============================] - 10s 43ms/step - loss: 0.2639 - accuracy: 0.9020 - val_loss: 0.3364 - val_accuracy: 0.8619
Epoch 4/10
228/228 [==============================] - 10s 43ms/step - loss: 0.2476 - accuracy: 0.9083 - val_loss: 0.3426 - val_accuracy: 0.8646
Epoch 5/10
228/228 [==============================] - 10s 44ms/step - loss: 0.2294 - accuracy: 0.9165 - val_loss: 0.3479 - val_accuracy: 0.8628
Epoch 6/10
228/228 [==============================] - 10s 43ms/step - loss: 0.2151 - accuracy: 0.9199 - val_loss: 0.3503 - val_accuracy: 0.8637
Epoch 7/10
228/228 [==============================] - 10s 43ms/step - loss: 0.2064 - accuracy: 0.9245 - val_loss: 0.3591 - val_accuracy: 0.8672
Epoch 8/10
228/228 [==============================] - 10s 44ms/step - loss: 0.1968 - accuracy: 0.9271 - val_loss: 0.3750 - val_accuracy: 0.8619
Epoch 9/10
228/228 [==============================] - 10s 43ms/step - loss: 0.1893 - accuracy: 0.9295 - val_loss: 0.3792 - val_accuracy: 0.8610
Epoch 10/10
228/228 [==============================] - 10s 43ms/step - loss: 0.1837 - accuracy: 0.9323 - val_loss: 0.3965 - val_accuracy: 0.8522
36/36 [==============================] - 0s 5ms/step - loss: 0.1764 - accuracy: 0.9331

102 seconds.

8 | Fri Oct 29 20:33:16 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
293/293 [==============================] - ETA: 0s - loss: 0.4481 - accuracy: 0.8262WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
293/293 [==============================] - 13s 41ms/step - loss: 0.4481 - accuracy: 0.8262 - val_loss: 0.3495 - val_accuracy: 0.8646
Epoch 2/10
293/293 [==============================] - 11s 38ms/step - loss: 0.2875 - accuracy: 0.8904 - val_loss: 0.3346 - val_accuracy: 0.8549
Epoch 3/10
293/293 [==============================] - 11s 38ms/step - loss: 0.2433 - accuracy: 0.9106 - val_loss: 0.3328 - val_accuracy: 0.8698
Epoch 4/10
293/293 [==============================] - 11s 37ms/step - loss: 0.2174 - accuracy: 0.9239 - val_loss: 0.3432 - val_accuracy: 0.8707
Epoch 5/10
293/293 [==============================] - 11s 37ms/step - loss: 0.1997 - accuracy: 0.9286 - val_loss: 0.3468 - val_accuracy: 0.8663
Epoch 6/10
293/293 [==============================] - 11s 37ms/step - loss: 0.1881 - accuracy: 0.9328 - val_loss: 0.3545 - val_accuracy: 0.8628
Epoch 7/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1726 - accuracy: 0.9388 - val_loss: 0.3595 - val_accuracy: 0.8654
Epoch 8/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1583 - accuracy: 0.9438 - val_loss: 0.3827 - val_accuracy: 0.8672
Epoch 9/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1534 - accuracy: 0.9458 - val_loss: 0.4082 - val_accuracy: 0.8522
Epoch 10/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1423 - accuracy: 0.9506 - val_loss: 0.4241 - val_accuracy: 0.8540
36/36 [==============================] - 0s 5ms/step - loss: 0.1642 - accuracy: 0.9340

114 seconds.

9 | Fri Oct 29 20:35:10 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 60).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 60).
121/121 [==============================] - ETA: 0s - loss: 0.5225 - accuracy: 0.7937WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 60).
121/121 [==============================] - 7s 44ms/step - loss: 0.5225 - accuracy: 0.7937 - val_loss: 0.3881 - val_accuracy: 0.8408
Epoch 2/10
121/121 [==============================] - 4s 36ms/step - loss: 0.3127 - accuracy: 0.8822 - val_loss: 0.3363 - val_accuracy: 0.8549
Epoch 3/10
121/121 [==============================] - 4s 35ms/step - loss: 0.2687 - accuracy: 0.9005 - val_loss: 0.3306 - val_accuracy: 0.8628
Epoch 4/10
121/121 [==============================] - 4s 35ms/step - loss: 0.2442 - accuracy: 0.9097 - val_loss: 0.3327 - val_accuracy: 0.8654
Epoch 5/10
121/121 [==============================] - 4s 37ms/step - loss: 0.2297 - accuracy: 0.9172 - val_loss: 0.3469 - val_accuracy: 0.8575
Epoch 6/10
121/121 [==============================] - 4s 35ms/step - loss: 0.2149 - accuracy: 0.9230 - val_loss: 0.3451 - val_accuracy: 0.8698
Epoch 7/10
121/121 [==============================] - 4s 35ms/step - loss: 0.2025 - accuracy: 0.9278 - val_loss: 0.3544 - val_accuracy: 0.8637
Epoch 8/10
121/121 [==============================] - 4s 35ms/step - loss: 0.1927 - accuracy: 0.9314 - val_loss: 0.3569 - val_accuracy: 0.8654
Epoch 9/10
121/121 [==============================] - 4s 35ms/step - loss: 0.1846 - accuracy: 0.9346 - val_loss: 0.3802 - val_accuracy: 0.8619
Epoch 10/10
121/121 [==============================] - 4s 35ms/step - loss: 0.1763 - accuracy: 0.9390 - val_loss: 0.3790 - val_accuracy: 0.8672
36/36 [==============================] - 0s 4ms/step - loss: 0.1651 - accuracy: 0.9445

46 seconds.

10 | Fri Oct 29 20:35:57 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
292/293 [============================>.] - ETA: 0s - loss: 0.4894 - accuracy: 0.7979WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
293/293 [==============================] - 13s 41ms/step - loss: 0.4893 - accuracy: 0.7980 - val_loss: 0.3789 - val_accuracy: 0.8487
Epoch 2/10
293/293 [==============================] - 11s 38ms/step - loss: 0.3099 - accuracy: 0.8841 - val_loss: 0.3355 - val_accuracy: 0.8690
Epoch 3/10
293/293 [==============================] - 11s 38ms/step - loss: 0.2687 - accuracy: 0.9014 - val_loss: 0.3441 - val_accuracy: 0.8663
Epoch 4/10
293/293 [==============================] - 11s 37ms/step - loss: 0.2412 - accuracy: 0.9136 - val_loss: 0.3441 - val_accuracy: 0.8628
Epoch 5/10
293/293 [==============================] - 11s 38ms/step - loss: 0.2220 - accuracy: 0.9211 - val_loss: 0.3556 - val_accuracy: 0.8672
Epoch 6/10
293/293 [==============================] - 11s 37ms/step - loss: 0.2072 - accuracy: 0.9253 - val_loss: 0.3836 - val_accuracy: 0.8575
Epoch 7/10
293/293 [==============================] - 11s 38ms/step - loss: 0.2015 - accuracy: 0.9268 - val_loss: 0.3759 - val_accuracy: 0.8575
Epoch 8/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1911 - accuracy: 0.9314 - val_loss: 0.3747 - val_accuracy: 0.8628
Epoch 9/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1837 - accuracy: 0.9337 - val_loss: 0.4213 - val_accuracy: 0.8531
Epoch 10/10
293/293 [==============================] - 11s 38ms/step - loss: 0.1774 - accuracy: 0.9381 - val_loss: 0.4022 - val_accuracy: 0.8549
36/36 [==============================] - 0s 5ms/step - loss: 0.1507 - accuracy: 0.9498

114 seconds.

11 | Fri Oct 29 20:37:50 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
158/158 [==============================] - 11s 62ms/step - loss: 0.5130 - accuracy: 0.8028 - val_loss: 0.3776 - val_accuracy: 0.8505
Epoch 2/10
158/158 [==============================] - 9s 56ms/step - loss: 0.3154 - accuracy: 0.8849 - val_loss: 0.3357 - val_accuracy: 0.8672
Epoch 3/10
158/158 [==============================] - 9s 57ms/step - loss: 0.2642 - accuracy: 0.9058 - val_loss: 0.3311 - val_accuracy: 0.8628
Epoch 4/10
158/158 [==============================] - 9s 57ms/step - loss: 0.2331 - accuracy: 0.9164 - val_loss: 0.3289 - val_accuracy: 0.8751
Epoch 5/10
158/158 [==============================] - 9s 57ms/step - loss: 0.2114 - accuracy: 0.9239 - val_loss: 0.3373 - val_accuracy: 0.8734
Epoch 6/10
158/158 [==============================] - 9s 56ms/step - loss: 0.1954 - accuracy: 0.9310 - val_loss: 0.3476 - val_accuracy: 0.8663
Epoch 7/10
158/158 [==============================] - 9s 56ms/step - loss: 0.1819 - accuracy: 0.9351 - val_loss: 0.3665 - val_accuracy: 0.8654
Epoch 8/10
158/158 [==============================] - 9s 57ms/step - loss: 0.1731 - accuracy: 0.9387 - val_loss: 0.3707 - val_accuracy: 0.8654
Epoch 9/10
158/158 [==============================] - 9s 56ms/step - loss: 0.1595 - accuracy: 0.9434 - val_loss: 0.3987 - val_accuracy: 0.8628
Epoch 10/10
158/158 [==============================] - 9s 56ms/step - loss: 0.1538 - accuracy: 0.9451 - val_loss: 0.3890 - val_accuracy: 0.8672
36/36 [==============================] - 0s 8ms/step - loss: 0.1549 - accuracy: 0.9454

93 seconds.

12 | Fri Oct 29 20:39:23 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
137/137 [==============================] - ETA: 0s - loss: 0.4911 - accuracy: 0.8020WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
137/137 [==============================] - 14s 95ms/step - loss: 0.4911 - accuracy: 0.8020 - val_loss: 0.3698 - val_accuracy: 0.8478
Epoch 2/10
137/137 [==============================] - 12s 90ms/step - loss: 0.3060 - accuracy: 0.8844 - val_loss: 0.3370 - val_accuracy: 0.8558
Epoch 3/10
137/137 [==============================] - 12s 89ms/step - loss: 0.2613 - accuracy: 0.9036 - val_loss: 0.3414 - val_accuracy: 0.8637
Epoch 4/10
137/137 [==============================] - 12s 89ms/step - loss: 0.2331 - accuracy: 0.9184 - val_loss: 0.3458 - val_accuracy: 0.8628
Epoch 5/10
137/137 [==============================] - 12s 90ms/step - loss: 0.2153 - accuracy: 0.9243 - val_loss: 0.3482 - val_accuracy: 0.8698
Epoch 6/10
137/137 [==============================] - 12s 89ms/step - loss: 0.1995 - accuracy: 0.9281 - val_loss: 0.3592 - val_accuracy: 0.8646
Epoch 7/10
137/137 [==============================] - 12s 89ms/step - loss: 0.1874 - accuracy: 0.9316 - val_loss: 0.3634 - val_accuracy: 0.8619
Epoch 8/10
137/137 [==============================] - 12s 89ms/step - loss: 0.1753 - accuracy: 0.9392 - val_loss: 0.3764 - val_accuracy: 0.8602
Epoch 9/10
137/137 [==============================] - 12s 87ms/step - loss: 0.1660 - accuracy: 0.9428 - val_loss: 0.3816 - val_accuracy: 0.8575
Epoch 10/10
137/137 [==============================] - 12s 87ms/step - loss: 0.1597 - accuracy: 0.9428 - val_loss: 0.3812 - val_accuracy: 0.8602
36/36 [==============================] - 0s 11ms/step - loss: 0.1389 - accuracy: 0.9516

125 seconds.

13 | Fri Oct 29 20:41:28 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
293/293 [==============================] - ETA: 0s - loss: 0.3943 - accuracy: 0.8274WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 180).
293/293 [==============================] - 34s 111ms/step - loss: 0.3943 - accuracy: 0.8274 - val_loss: 0.3365 - val_accuracy: 0.8619
Epoch 2/10
293/293 [==============================] - 31s 107ms/step - loss: 0.2779 - accuracy: 0.8919 - val_loss: 0.3218 - val_accuracy: 0.8690
Epoch 3/10
293/293 [==============================] - 32s 108ms/step - loss: 0.2397 - accuracy: 0.9102 - val_loss: 0.3233 - val_accuracy: 0.8725
Epoch 4/10
293/293 [==============================] - 31s 107ms/step - loss: 0.2112 - accuracy: 0.9210 - val_loss: 0.3292 - val_accuracy: 0.8681
Epoch 5/10
293/293 [==============================] - 31s 107ms/step - loss: 0.1937 - accuracy: 0.9277 - val_loss: 0.3462 - val_accuracy: 0.8637
Epoch 6/10
293/293 [==============================] - 31s 107ms/step - loss: 0.1733 - accuracy: 0.9373 - val_loss: 0.3893 - val_accuracy: 0.8558
Epoch 7/10
293/293 [==============================] - 31s 107ms/step - loss: 0.1610 - accuracy: 0.9409 - val_loss: 0.3831 - val_accuracy: 0.8593
Epoch 8/10
293/293 [==============================] - 31s 107ms/step - loss: 0.1563 - accuracy: 0.9427 - val_loss: 0.4044 - val_accuracy: 0.8584
Epoch 9/10
293/293 [==============================] - 32s 108ms/step - loss: 0.1386 - accuracy: 0.9500 - val_loss: 0.4280 - val_accuracy: 0.8593
Epoch 10/10
293/293 [==============================] - 32s 108ms/step - loss: 0.1275 - accuracy: 0.9531 - val_loss: 0.4260 - val_accuracy: 0.8566
36/36 [==============================] - 1s 15ms/step - loss: 0.1372 - accuracy: 0.9516

318 seconds.

14 | Fri Oct 29 20:46:47 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
186/186 [==============================] - ETA: 0s - loss: 0.4911 - accuracy: 0.8059WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
186/186 [==============================] - 17s 83ms/step - loss: 0.4911 - accuracy: 0.8059 - val_loss: 0.3790 - val_accuracy: 0.8417
Epoch 2/10
186/186 [==============================] - 15s 79ms/step - loss: 0.3060 - accuracy: 0.8830 - val_loss: 0.3441 - val_accuracy: 0.8619
Epoch 3/10
186/186 [==============================] - 15s 82ms/step - loss: 0.2594 - accuracy: 0.9042 - val_loss: 0.3391 - val_accuracy: 0.8646
Epoch 4/10
186/186 [==============================] - 15s 81ms/step - loss: 0.2360 - accuracy: 0.9158 - val_loss: 0.3426 - val_accuracy: 0.8646
Epoch 5/10
186/186 [==============================] - 15s 82ms/step - loss: 0.2219 - accuracy: 0.9191 - val_loss: 0.3527 - val_accuracy: 0.8619
Epoch 6/10
186/186 [==============================] - 15s 81ms/step - loss: 0.2065 - accuracy: 0.9271 - val_loss: 0.3547 - val_accuracy: 0.8646
Epoch 7/10
186/186 [==============================] - 15s 79ms/step - loss: 0.1965 - accuracy: 0.9287 - val_loss: 0.3688 - val_accuracy: 0.8637
Epoch 8/10
186/186 [==============================] - 15s 81ms/step - loss: 0.1869 - accuracy: 0.9335 - val_loss: 0.3676 - val_accuracy: 0.8646
Epoch 9/10
186/186 [==============================] - 14s 75ms/step - loss: 0.1779 - accuracy: 0.9358 - val_loss: 0.3869 - val_accuracy: 0.8610
Epoch 10/10
186/186 [==============================] - 14s 76ms/step - loss: 0.1732 - accuracy: 0.9384 - val_loss: 0.3923 - val_accuracy: 0.8584
36/36 [==============================] - 0s 10ms/step - loss: 0.1889 - accuracy: 0.9384

152 seconds.

15 | Fri Oct 29 20:49:18 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 90).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 90).
228/228 [==============================] - ETA: 0s - loss: 0.4360 - accuracy: 0.8122WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 90).
228/228 [==============================] - 13s 53ms/step - loss: 0.4360 - accuracy: 0.8122 - val_loss: 0.3466 - val_accuracy: 0.8646
Epoch 2/10
228/228 [==============================] - 11s 49ms/step - loss: 0.2854 - accuracy: 0.8901 - val_loss: 0.3429 - val_accuracy: 0.8584
Epoch 3/10
228/228 [==============================] - 11s 49ms/step - loss: 0.2514 - accuracy: 0.9036 - val_loss: 0.3227 - val_accuracy: 0.8672
Epoch 4/10
228/228 [==============================] - 11s 48ms/step - loss: 0.2267 - accuracy: 0.9170 - val_loss: 0.3528 - val_accuracy: 0.8646
Epoch 5/10
228/228 [==============================] - 11s 49ms/step - loss: 0.2078 - accuracy: 0.9235 - val_loss: 0.3502 - val_accuracy: 0.8698
Epoch 6/10
228/228 [==============================] - 11s 48ms/step - loss: 0.1931 - accuracy: 0.9289 - val_loss: 0.3500 - val_accuracy: 0.8637
Epoch 7/10
228/228 [==============================] - 11s 48ms/step - loss: 0.1799 - accuracy: 0.9328 - val_loss: 0.3631 - val_accuracy: 0.8654
Epoch 8/10
228/228 [==============================] - 11s 48ms/step - loss: 0.1752 - accuracy: 0.9361 - val_loss: 0.3759 - val_accuracy: 0.8646
Epoch 9/10
228/228 [==============================] - 11s 49ms/step - loss: 0.1588 - accuracy: 0.9405 - val_loss: 0.3921 - val_accuracy: 0.8602
Epoch 10/10
228/228 [==============================] - 11s 48ms/step - loss: 0.1513 - accuracy: 0.9453 - val_loss: 0.4286 - val_accuracy: 0.8681
36/36 [==============================] - 0s 6ms/step - loss: 0.1805 - accuracy: 0.9419

113 seconds.

16 | Fri Oct 29 20:51:12 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
2046/2046 [==============================] - ETA: 0s - loss: 0.3639 - accuracy: 0.8554WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 150).
2046/2046 [==============================] - 143s 69ms/step - loss: 0.3639 - accuracy: 0.8554 - val_loss: 0.3308 - val_accuracy: 0.8646
Epoch 2/10
2046/2046 [==============================] - 140s 68ms/step - loss: 0.2585 - accuracy: 0.9003 - val_loss: 0.3229 - val_accuracy: 0.8646
Epoch 3/10
2046/2046 [==============================] - 140s 68ms/step - loss: 0.2177 - accuracy: 0.9185 - val_loss: 0.3326 - val_accuracy: 0.8672
Epoch 4/10
2046/2046 [==============================] - 139s 68ms/step - loss: 0.1859 - accuracy: 0.9288 - val_loss: 0.3662 - val_accuracy: 0.8663
Epoch 5/10
2046/2046 [==============================] - 139s 68ms/step - loss: 0.1608 - accuracy: 0.9416 - val_loss: 0.3622 - val_accuracy: 0.8751
Epoch 6/10
2046/2046 [==============================] - 148s 72ms/step - loss: 0.1444 - accuracy: 0.9468 - val_loss: 0.3816 - val_accuracy: 0.8725
Epoch 7/10
2046/2046 [==============================] - 149s 73ms/step - loss: 0.1261 - accuracy: 0.9562 - val_loss: 0.3978 - val_accuracy: 0.8619
Epoch 8/10
2046/2046 [==============================] - 149s 73ms/step - loss: 0.1159 - accuracy: 0.9607 - val_loss: 0.4460 - val_accuracy: 0.8672
Epoch 9/10
2046/2046 [==============================] - 152s 74ms/step - loss: 0.1047 - accuracy: 0.9647 - val_loss: 0.4425 - val_accuracy: 0.8663
Epoch 10/10
2046/2046 [==============================] - 150s 73ms/step - loss: 0.0957 - accuracy: 0.9687 - val_loss: 0.4842 - val_accuracy: 0.8522
36/36 [==============================] - 0s 10ms/step - loss: 0.1200 - accuracy: 0.9665

1450 seconds.

17 | Fri Oct 29 21:15:21 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
409/410 [============================>.] - ETA: 0s - loss: 0.3917 - accuracy: 0.8346WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 70).
410/410 [==============================] - 18s 40ms/step - loss: 0.3916 - accuracy: 0.8347 - val_loss: 0.3642 - val_accuracy: 0.8391
Epoch 2/10
410/410 [==============================] - 16s 38ms/step - loss: 0.2763 - accuracy: 0.8928 - val_loss: 0.3269 - val_accuracy: 0.8610
Epoch 3/10
410/410 [==============================] - 16s 39ms/step - loss: 0.2445 - accuracy: 0.9080 - val_loss: 0.3416 - val_accuracy: 0.8672
Epoch 4/10
410/410 [==============================] - 16s 38ms/step - loss: 0.2213 - accuracy: 0.9182 - val_loss: 0.3615 - val_accuracy: 0.8610
Epoch 5/10
410/410 [==============================] - 16s 38ms/step - loss: 0.2041 - accuracy: 0.9249 - val_loss: 0.3485 - val_accuracy: 0.8672
Epoch 6/10
410/410 [==============================] - 16s 38ms/step - loss: 0.1854 - accuracy: 0.9325 - val_loss: 0.3625 - val_accuracy: 0.8602
Epoch 7/10
410/410 [==============================] - 16s 38ms/step - loss: 0.1728 - accuracy: 0.9386 - val_loss: 0.3646 - val_accuracy: 0.8646
Epoch 8/10
410/410 [==============================] - 16s 38ms/step - loss: 0.1609 - accuracy: 0.9419 - val_loss: 0.3851 - val_accuracy: 0.8540
Epoch 9/10
410/410 [==============================] - 15s 38ms/step - loss: 0.1496 - accuracy: 0.9457 - val_loss: 0.3934 - val_accuracy: 0.8584
Epoch 10/10
410/410 [==============================] - 16s 38ms/step - loss: 0.1488 - accuracy: 0.9456 - val_loss: 0.4327 - val_accuracy: 0.8619
36/36 [==============================] - 0s 6ms/step - loss: 0.1461 - accuracy: 0.9507

160 seconds.

18 | Fri Oct 29 21:18:01 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
158/158 [==============================] - ETA: 0s - loss: 0.4333 - accuracy: 0.8271WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 140).
158/158 [==============================] - 16s 92ms/step - loss: 0.4333 - accuracy: 0.8271 - val_loss: 0.3393 - val_accuracy: 0.8575
Epoch 2/10
158/158 [==============================] - 14s 87ms/step - loss: 0.2834 - accuracy: 0.8913 - val_loss: 0.3305 - val_accuracy: 0.8646
Epoch 3/10
158/158 [==============================] - 14s 87ms/step - loss: 0.2473 - accuracy: 0.9081 - val_loss: 0.3337 - val_accuracy: 0.8698
Epoch 4/10
158/158 [==============================] - 14s 85ms/step - loss: 0.2217 - accuracy: 0.9177 - val_loss: 0.3295 - val_accuracy: 0.8751
Epoch 5/10
158/158 [==============================] - 14s 85ms/step - loss: 0.1995 - accuracy: 0.9282 - val_loss: 0.3437 - val_accuracy: 0.8654
Epoch 6/10
158/158 [==============================] - 13s 85ms/step - loss: 0.1853 - accuracy: 0.9317 - val_loss: 0.3563 - val_accuracy: 0.8646
Epoch 7/10
158/158 [==============================] - 13s 85ms/step - loss: 0.1714 - accuracy: 0.9393 - val_loss: 0.3808 - val_accuracy: 0.8619
Epoch 8/10
158/158 [==============================] - 13s 85ms/step - loss: 0.1571 - accuracy: 0.9454 - val_loss: 0.3925 - val_accuracy: 0.8584
Epoch 9/10
158/158 [==============================] - 13s 85ms/step - loss: 0.1464 - accuracy: 0.9494 - val_loss: 0.3961 - val_accuracy: 0.8602
Epoch 10/10
158/158 [==============================] - 14s 86ms/step - loss: 0.1404 - accuracy: 0.9509 - val_loss: 0.4140 - val_accuracy: 0.8593
36/36 [==============================] - 0s 10ms/step - loss: 0.1481 - accuracy: 0.9560

139 seconds.

19 | Fri Oct 29 21:20:20 2021 | lowest loss so far: 0.1067 (run 2)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 110).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 110).
2046/2046 [==============================] - ETA: 0s - loss: 0.3559 - accuracy: 0.8482WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 110).
2046/2046 [==============================] - 118s 57ms/step - loss: 0.3559 - accuracy: 0.8482 - val_loss: 0.3188 - val_accuracy: 0.8760
Epoch 2/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.2543 - accuracy: 0.9034 - val_loss: 0.3200 - val_accuracy: 0.8663
Epoch 3/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.2162 - accuracy: 0.9167 - val_loss: 0.3209 - val_accuracy: 0.8681
Epoch 4/10
2046/2046 [==============================] - 114s 56ms/step - loss: 0.1884 - accuracy: 0.9294 - val_loss: 0.3293 - val_accuracy: 0.8681
Epoch 5/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.1643 - accuracy: 0.9401 - val_loss: 0.3538 - val_accuracy: 0.8707
Epoch 6/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.1475 - accuracy: 0.9459 - val_loss: 0.3993 - val_accuracy: 0.8628
Epoch 7/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.1321 - accuracy: 0.9524 - val_loss: 0.4442 - val_accuracy: 0.8619
Epoch 8/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.1194 - accuracy: 0.9581 - val_loss: 0.4461 - val_accuracy: 0.8514
Epoch 9/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.1087 - accuracy: 0.9640 - val_loss: 0.4456 - val_accuracy: 0.8593
Epoch 10/10
2046/2046 [==============================] - 115s 56ms/step - loss: 0.0970 - accuracy: 0.9670 - val_loss: 0.5412 - val_accuracy: 0.8531
36/36 [==============================] - 0s 9ms/step - loss: 0.1051 - accuracy: 0.9674

1153 seconds.

20 | Fri Oct 29 21:39:33 2021 | lowest loss so far: 0.1051 (run 19)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 170).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 170).
228/228 [==============================] - ETA: 0s - loss: 0.4778 - accuracy: 0.8154WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 170).
228/228 [==============================] - 24s 100ms/step - loss: 0.4778 - accuracy: 0.8154 - val_loss: 0.3681 - val_accuracy: 0.8531
Epoch 2/10
228/228 [==============================] - 22s 96ms/step - loss: 0.3015 - accuracy: 0.8870 - val_loss: 0.3429 - val_accuracy: 0.8610
Epoch 3/10
228/228 [==============================] - 22s 95ms/step - loss: 0.2565 - accuracy: 0.9088 - val_loss: 0.3356 - val_accuracy: 0.8637
Epoch 4/10
228/228 [==============================] - 22s 97ms/step - loss: 0.2289 - accuracy: 0.9164 - val_loss: 0.3421 - val_accuracy: 0.8610
Epoch 5/10
228/228 [==============================] - 22s 95ms/step - loss: 0.2162 - accuracy: 0.9193 - val_loss: 0.3563 - val_accuracy: 0.8584
Epoch 6/10
228/228 [==============================] - 22s 95ms/step - loss: 0.1988 - accuracy: 0.9264 - val_loss: 0.3623 - val_accuracy: 0.8619
Epoch 7/10
228/228 [==============================] - 22s 97ms/step - loss: 0.1896 - accuracy: 0.9293 - val_loss: 0.3867 - val_accuracy: 0.8628
Epoch 8/10
228/228 [==============================] - 22s 95ms/step - loss: 0.1748 - accuracy: 0.9365 - val_loss: 0.4037 - val_accuracy: 0.8584
Epoch 9/10
228/228 [==============================] - 22s 95ms/step - loss: 0.1726 - accuracy: 0.9356 - val_loss: 0.3851 - val_accuracy: 0.8646
Epoch 10/10
228/228 [==============================] - 22s 96ms/step - loss: 0.1622 - accuracy: 0.9397 - val_loss: 0.3945 - val_accuracy: 0.8619
36/36 [==============================] - 0s 11ms/step - loss: 0.1534 - accuracy: 0.9481

222 seconds.

21 | Fri Oct 29 21:43:15 2021 | lowest loss so far: 0.1051 (run 19)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 130).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 130).
410/410 [==============================] - ETA: 0s - loss: 0.3823 - accuracy: 0.8378WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 130).
410/410 [==============================] - 33s 76ms/step - loss: 0.3823 - accuracy: 0.8378 - val_loss: 0.3331 - val_accuracy: 0.8628
Epoch 2/10
410/410 [==============================] - 30s 74ms/step - loss: 0.2686 - accuracy: 0.8959 - val_loss: 0.3288 - val_accuracy: 0.8672
Epoch 3/10
410/410 [==============================] - 30s 74ms/step - loss: 0.2306 - accuracy: 0.9139 - val_loss: 0.3267 - val_accuracy: 0.8663
Epoch 4/10
410/410 [==============================] - 30s 74ms/step - loss: 0.2063 - accuracy: 0.9235 - val_loss: 0.3392 - val_accuracy: 0.8698
Epoch 5/10
410/410 [==============================] - 30s 74ms/step - loss: 0.1862 - accuracy: 0.9323 - val_loss: 0.3532 - val_accuracy: 0.8619
Epoch 6/10
410/410 [==============================] - 30s 74ms/step - loss: 0.1645 - accuracy: 0.9394 - val_loss: 0.3831 - val_accuracy: 0.8654
Epoch 7/10
410/410 [==============================] - 30s 74ms/step - loss: 0.1573 - accuracy: 0.9405 - val_loss: 0.4077 - val_accuracy: 0.8584
Epoch 8/10
410/410 [==============================] - 30s 74ms/step - loss: 0.1415 - accuracy: 0.9500 - val_loss: 0.3938 - val_accuracy: 0.8602
Epoch 9/10
410/410 [==============================] - 30s 74ms/step - loss: 0.1291 - accuracy: 0.9537 - val_loss: 0.4478 - val_accuracy: 0.8584
Epoch 10/10
410/410 [==============================] - 30s 74ms/step - loss: 0.1294 - accuracy: 0.9545 - val_loss: 0.4257 - val_accuracy: 0.8558
36/36 [==============================] - 0s 10ms/step - loss: 0.1157 - accuracy: 0.9648

307 seconds.

22 | Fri Oct 29 21:48:22 2021 | lowest loss so far: 0.1051 (run 19)

Epoch 1/10
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 120).
WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 120).
2046/2046 [==============================] - ETA: 0s - loss: 0.3521 - accuracy: 0.8548WARNING:tensorflow:Model was constructed with shape (None, 100) for input KerasTensor(type_spec=TensorSpec(shape=(None, 100), dtype=tf.float32, name='input'), name='input', description="created by layer 'input'"), but it was called on an input with incompatible shape (None, 120).
2046/2046 [==============================] - 128s 62ms/step - loss: 0.3521 - accuracy: 0.8548 - val_loss: 0.3300 - val_accuracy: 0.8593
Epoch 2/10
2046/2046 [==============================] - 125s 61ms/step - loss: 0.2547 - accuracy: 0.9019 - val_loss: 0.3153 - val_accuracy: 0.8716
Epoch 3/10
2046/2046 [==============================] - 124s 61ms/step - loss: 0.2162 - accuracy: 0.9188 - val_loss: 0.3266 - val_accuracy: 0.8610
Epoch 4/10
2046/2046 [==============================] - 124s 61ms/step - loss: 0.1849 - accuracy: 0.9313 - val_loss: 0.3526 - val_accuracy: 0.8672
Epoch 5/10
2046/2046 [==============================] - 124s 61ms/step - loss: 0.1614 - accuracy: 0.9420 - val_loss: 0.3861 - val_accuracy: 0.8672
Epoch 6/10
2046/2046 [==============================] - 124s 61ms/step - loss: 0.1450 - accuracy: 0.9474 - val_loss: 0.3962 - val_accuracy: 0.8663
Epoch 7/10
2046/2046 [==============================] - ETA: 0s - loss: 0.1266 - accuracy: 0.9554